name: Connect Git Actions and Testing

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          docker compose up -d --build

      - name: Wait for services to be ready 
        run: sleep 10

      - name: Run Pytest inside the container
        run: |
          docker exec tawk_app pytest /app/test --disable-warnings

      - name: Stop Docker containers
        run: docker-compose down
